// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for macos');
      case TargetPlatform.windows:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for windows');
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCy6QKu-JqNdTfIhgQO5LW4sFoEzuPwPI',
    appId: '1:1073869961803:web:90dbef4f82fa1f95abbd02',
    messagingSenderId: '1073869961803',
    projectId: 'tagit-emergency',
    authDomain: 'tagit-emergency.firebaseapp.com',
    storageBucket: 'tagit-emergency.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRd7Shxna9gUVLSP6CpoO-pvhfvNbNMs',
    appId: '1:1067628919771:android:3cd6cde42baff60efc45fe',
    messagingSenderId: '1067628919771',
    projectId: 'tagit-emergency',
    storageBucket: 'tagit-emergency.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCy6QKu-JqNdTfIhgQO5LW4sFoEzuPwPI',
    appId: '1:1073869961803:ios:abcd1234',
    messagingSenderId: '1073869961803',
    projectId: 'tagit-emergency',
    storageBucket: 'tagit-emergency.firebasestorage.app',
    iosBundleId: 'com.tagit.emergency',
  );
}
